# ==== pytest ====
[tool.pytest.ini_options]
minversion = "8.0"
python_files = [
    "tests.py",
    "test_*.py",
]
required_plugins = ["pytest-factoryboy"]

# ==== Coverage ====
[tool.coverage.run]
include = ["src/**"]
omit = ["*/migrations/*", "*/tests/*"]


# ==== black ====
[tool.black]
line-length = 88
target-version = ['py310']


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 88
known_first_party = [
    "src",
]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]


# ==== mypy ====
[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = [
    "mypy_drf_plugin.main",
]

[tool.pylint.FORMAT]
max-line-length = 88

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "missing-docstring",
    "invalid-name",
]

[tool.pylint.DESIGN]
max-parents = 13

[tool.pylint.TYPECHECK]
generated-members = [
    "REQUEST",
    "acl_users",
    "aq_parent",
    "[a-zA-Z]+_set{1,2}",
    "save",
    "delete",
]
